monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_http_codes: [404, 405]
            buffer_size: 200
        grouped:
          type:    group
          members: [streamed, deduplicated]
        streamed:
          type:  stream
          path:  '%kernel.logs_dir%/%kernel.environment%.log'
          level: debug
        deduplicated:
          type:    deduplication
          handler: symfony_mailer
          time: 600
        symfony_mailer:
          type:         symfony_mailer
          from_email:   '%env(MAILER_FROM)%'
          to_email:     '%env(ADMIN_EMAIL)%'
          subject:      'An Error Occurred! %%message%%'
          level:        debug
          formatter:    monolog.formatter.html
          content_type: text/html
        console:
          type: console
          process_psr_3_messages: false
          channels: ["!event", "!doctrine", "!event"]
